"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:07:55.195323
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_employee_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('emp_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_employee_profiles_emp_no'), 'hr_employee_profiles', ['emp_no'], unique=True)
    op.create_index(op.f('ix_hr_employee_profiles_name'), 'hr_employee_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_hr_employee_profiles_status'), 'hr_employee_profiles', ['status'], unique=False)
    op.create_table('hr_attendance_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('att_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'att_date', name='uq_attendance_emp_date')
    )
    op.create_index(op.f('ix_hr_attendance_records_att_date'), 'hr_attendance_records', ['att_date'], unique=False)
    op.create_index(op.f('ix_hr_attendance_records_employee_id'), 'hr_attendance_records', ['employee_id'], unique=False)
    op.create_table('hr_change_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('from_department', sa.String(length=64), nullable=False),
    sa.Column('to_department', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_change_requests_change_type'), 'hr_change_requests', ['change_type'], unique=False)
    op.create_index(op.f('ix_hr_change_requests_employee_id'), 'hr_change_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_change_requests_status'), 'hr_change_requests', ['status'], unique=False)
    op.create_table('hr_leave_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('leave_type', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_leave_requests_employee_id'), 'hr_leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_leave_requests_status'), 'hr_leave_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_leave_requests_status'), table_name='hr_leave_requests')
    op.drop_index(op.f('ix_hr_leave_requests_employee_id'), table_name='hr_leave_requests')
    op.drop_table('hr_leave_requests')
    op.drop_index(op.f('ix_hr_change_requests_status'), table_name='hr_change_requests')
    op.drop_index(op.f('ix_hr_change_requests_employee_id'), table_name='hr_change_requests')
    op.drop_index(op.f('ix_hr_change_requests_change_type'), table_name='hr_change_requests')
    op.drop_table('hr_change_requests')
    op.drop_index(op.f('ix_hr_attendance_records_employee_id'), table_name='hr_attendance_records')
    op.drop_index(op.f('ix_hr_attendance_records_att_date'), table_name='hr_attendance_records')
    op.drop_table('hr_attendance_records')
    op.drop_index(op.f('ix_hr_employee_profiles_status'), table_name='hr_employee_profiles')
    op.drop_index(op.f('ix_hr_employee_profiles_name'), table_name='hr_employee_profiles')
    op.drop_index(op.f('ix_hr_employee_profiles_emp_no'), table_name='hr_employee_profiles')
    op.drop_table('hr_employee_profiles')
    # ### end Alembic commands ###
